GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Blog3",
    "author": "Author",
    "url": "localhost/2",
    "likes": 2
}